# Generated by Django 4.2.29 on 2026-03-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='break_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
