# Generated by Django 4.2.29 on 2026-03-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_break_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='accumulated_gross_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
